# Generated by Django 5.2.4 on 2025-08-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='detatime_created',
            new_name='datetime_created',
        ),
    ]
